name: digital_clock
description: Digital clock.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper
  cupertino_icons: ^0.1.2
  video_player: ^0.10.4+1
  spritewidget: ^0.9.23

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/clouds-0.png
    - assets/clouds-1.png
    - assets/ray.png
    - assets/sun.png
    - assets/weathersprites.json
    - assets/weathersprites.png
